version: '3'
services:
  webapi:
    image: allin:postgres
    links:
      - postgres
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: local
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
